import type { Store } from "@/types/store";
import type { Deal } from "@/types/deal";
import type { Handoff } from "@/types/handoff";
import { daysAgo } from "@/lib/utils/date";

/**
 * DB seed 用の冪等データ。
 *
 * `scripts/seed.ts` および `lib/actions/data-actions.ts` (Reset / Import) が
 * 参照する SoT。Mock 経路廃止 (Issue #39) に伴い `lib/mock/seed.ts` から
 * 移植した。
 *
 * 設計判断:
 * - `assigned_planner_user_id` / `assigned_sales_user_id` は **全て null** とする。
 *   profiles テーブルへの seed は別運用 (Supabase Auth + handle_new_user trigger)
 *   で行うため、ここで固定 UUID を埋めると FK 違反のリスクがある。
 *   実運用で担当者を紐付けたい場合は別途 UPDATE する運用となる。
 * - 依存は `@/types/*` と `@/lib/utils/date` のみ。`@/lib/db/client.ts` や
 *   `@/lib/db/schema.ts` には依存しないことで、`data-actions.ts` の動的 import
 *   制約 (Issue 2) を壊さない。
 */

export const SEED_STORES: readonly Store[] = [
  {
    id: "store_001",
    name: "導楽",
    prefecture: "神奈川県",
    city: "川崎市中原区",
    address: "新丸子駅周辺",
    genre: "居酒屋",
    priority: "高",
    stage: "調査済み",
    map_url: "https://maps.google.com/?q=導楽+新丸子",
    site_url: "",
    instagram_url: "",
    phone: "",
    has_contact_form: "なし",
    channel: "テレアポ推奨",
    target_service: "MEO,HP",
    memo:
      "食べログURL: https://tabelog.com/kanagawa/A1405/A140504/14096697/\nお刺身評価高いが情報発信弱い。公式サイト・Instagram確認できず。",
    assigned_planner_user_id: null,
    assigned_sales_user_id: null,
    review_count: 12,
    review_avg: 3.4,
    operator_type: "未設定",
    operator_name: "",
    ai_analysis_result: null,
    lat: 35.5836,
    lng: 139.6571,
    basic_info: {},
    google_place_id: null,
    appointment_acquired_date: null,
    next_action_date: null,
    next_action_note: null,
    created_at: daysAgo(3),
    updated_at: daysAgo(1),
  },
  {
    id: "store_002",
    name: "CAFE VERDE",
    prefecture: "東京都",
    city: "世田谷区",
    address: "三軒茶屋2-14-5",
    genre: "カフェ",
    priority: "中",
    stage: "調査済み",
    map_url: "https://maps.google.com/?q=CAFE+VERDE+三軒茶屋",
    site_url: "https://example.com/cafeverde",
    instagram_url: "https://instagram.com/cafeverde",
    phone: "03-XXXX-XXXX",
    has_contact_form: "あり",
    channel: "DM推奨",
    target_service: "MEO,インスタ",
    memo:
      "公式サイトに問い合わせフォームあり。Instagram開設済みだが更新3ヶ月停止。",
    assigned_planner_user_id: null,
    assigned_sales_user_id: null,
    review_count: 28,
    review_avg: 3.8,
    operator_type: "未設定",
    operator_name: "",
    ai_analysis_result: null,
    lat: 35.6432,
    lng: 139.6709,
    basic_info: {},
    google_place_id: null,
    appointment_acquired_date: null,
    next_action_date: null,
    next_action_note: null,
    created_at: daysAgo(5),
    updated_at: daysAgo(2),
  },
  {
    id: "store_003",
    name: "炭火焼鳥 鶴丸",
    prefecture: "神奈川県",
    city: "横浜市港北区",
    address: "日吉本町1-2-3",
    genre: "その他",
    priority: "高",
    stage: "架電済み",
    map_url: "https://maps.google.com/?q=炭火焼鳥鶴丸+日吉",
    site_url: "",
    instagram_url: "",
    phone: "045-XXX-XXXX",
    has_contact_form: "なし",
    channel: "テレアポ推奨",
    target_service: "MEO,HP,動画",
    memo:
      "電話のみ。Googleマップの写真が古い。口コミ返信ゼロ。オーナーは集客に困っていると推測。",
    assigned_planner_user_id: null,
    assigned_sales_user_id: null,
    review_count: 45,
    review_avg: 4.1,
    operator_type: "未設定",
    operator_name: "",
    ai_analysis_result: null,
    lat: 35.5526,
    lng: 139.6469,
    basic_info: {},
    google_place_id: null,
    appointment_acquired_date: daysAgo(4),
    next_action_date: daysAgo(-3),
    next_action_note: "見積内容のフォロー電話。予算感 (月2〜3万) に合わせた再提案を検討。",
    created_at: daysAgo(8),
    updated_at: daysAgo(1),
  },
  {
    id: "store_004",
    name: "らーめん 心",
    prefecture: "東京都",
    city: "大田区",
    address: "蒲田5-8-11",
    genre: "ラーメン",
    priority: "低",
    stage: "未調査",
    map_url: "",
    site_url: "",
    instagram_url: "",
    phone: "03-XXXX-XXXX",
    has_contact_form: "未確認",
    channel: "未判定",
    target_service: "おまかせ",
    memo: "紹介案件。詳細調査未着手。",
    assigned_planner_user_id: null,
    assigned_sales_user_id: null,
    review_count: 8,
    review_avg: 3.9,
    operator_type: "未設定",
    operator_name: "",
    ai_analysis_result: null,
    lat: null,
    lng: null,
    basic_info: {},
    google_place_id: null,
    appointment_acquired_date: null,
    next_action_date: null,
    next_action_note: null,
    created_at: daysAgo(1),
    updated_at: daysAgo(1),
  },
  {
    id: "store_005",
    name: "トラットリア SOLE",
    prefecture: "東京都",
    city: "目黒区",
    address: "中目黒1-5-8",
    genre: "イタリアン",
    priority: "中",
    stage: "架電済み",
    map_url: "https://maps.google.com/?q=トラットリアSOLE+中目黒",
    site_url: "https://example.com/sole",
    instagram_url: "https://instagram.com/trattoriasole",
    phone: "03-XXXX-XXXX",
    has_contact_form: "あり",
    channel: "DM推奨",
    target_service: "HP,MEO,インスタ",
    memo:
      "受注済み。HP制作+MEO+Instagram指南 セット。初期費用398,000円+月額22,000円。",
    assigned_planner_user_id: null,
    assigned_sales_user_id: null,
    review_count: 63,
    review_avg: 4.3,
    operator_type: "未設定",
    operator_name: "",
    ai_analysis_result: null,
    lat: 35.6444,
    lng: 139.6985,
    basic_info: {},
    google_place_id: null,
    appointment_acquired_date: daysAgo(12),
    next_action_date: null,
    next_action_note: null,
    created_at: daysAgo(14),
    updated_at: daysAgo(0),
  },
];

export const SEED_DEALS: readonly Deal[] = [
  {
    id: "deal_001",
    store_id: "store_003",
    store_name: "炭火焼鳥 鶴丸",
    date: daysAgo(2),
    meeting_type: "対面",
    discussion:
      "オーナーと初回商談。開業2年で新規客が減っているとのこと。Googleマップは登録しているが写真・情報が古いまま。予算は月2〜3万で考えている。前向き。",
    proposal: "MEO対策(初期+月額)+ショート動画3本セット",
    estimate_amount: 110000,
    order_amount: null,
    lost_reason: "",
    status: "見積提出",
    assigned_sales_user_id: null,
    activity_memo: null,
    next_action_date: null,
    next_action_type: null,
    next_action_note: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    id: "deal_002",
    store_id: "store_005",
    store_name: "トラットリア SOLE",
    date: daysAgo(10),
    meeting_type: "オンライン",
    discussion:
      "開業1年目。口コミは良いがHPがなく、予約はInstagramのDMだけ。HP作成とMEOとインスタ整備を全部まとめてやりたいとのこと。",
    proposal: "HP松プラン(撮影あり)+MEOセット+Instagram指南",
    estimate_amount: 453000,
    order_amount: 453000,
    lost_reason: "",
    status: "受注",
    assigned_sales_user_id: null,
    activity_memo: null,
    next_action_date: null,
    next_action_type: null,
    next_action_note: null,
    created_at: daysAgo(10),
    updated_at: daysAgo(0),
  },
];

export const SEED_HANDOFFS: readonly Handoff[] = [
  {
    id: "hand_001",
    store_id: "store_005",
    store_name: "トラットリア SOLE",
    deal_id: "deal_002",
    contract_services:
      "HP制作(松プラン・撮影あり)、MEO対策(初期+月額)、Instagram運用指南",
    initial_fee: 453000,
    monthly_fee: 22000,
    contract_period: "1年(自動更新)",
    expected_result: "Googleマップ上位表示、新規来店月20件増、Instagram再起動",
    contract_owner: "佐藤(Firstweb)",
    caution:
      "オーナーの山田さんはSNS不慣れ。初回説明は丁寧に。撮影日は土曜日のみ可。",
    ng_items: "SNS上での競合他社の名前出しNG。価格交渉の話は社長に戻すこと。",
    due_date: "2026-05-15",
    materials_status: "写真素材・ロゴはオーナー提供予定。撮影は2026-04-20予定。",
    ops_assignee: "小泉",
    contract_date: daysAgo(0),
    payment_confirmed: daysAgo(0),
    status: "完了",
    created_at: daysAgo(0),
    updated_at: daysAgo(0),
  },
];
